Repository TOY2-12/LangChat, pull requests merged in 2023-11, with the labels that each got.

#7 Style: 메인 및 서브 레이아웃 적용
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  public/logo-horizontal-w.png
  public/logo-horizontal.png
  public/logo-square-w.png
  public/logo-square.png
  public/mobile-app-bg.jpg
  src/App.tsx
  src/atoms.ts
  src/components/auth/SignUpForm.tsx
  src/components/common/AuthLayout.tsx
  src/components/common/Layout.tsx
  src/components/common/Sidebar.tsx
  src/index.css
  src/index.tsx
  src/libs/axios.ts
  src/libs/mui.ts
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/styles/AuthStyles.ts
  src/styles/SidebarStyles.ts
  src/types/User.ts
Labels: enhancement

#29 Feat: 오픈채팅방, 채팅방 친구 초대 UI 생성
  src/App.tsx
  src/components/common/Sidebar.tsx
  src/components/openchat/MenuToggle.module.css
  src/components/openchat/MenuToggle.tsx
  src/components/openchat/OpenchatCategory.tsx
  src/components/openchat/OpenchatInviteFriendItem.tsx
  src/components/openchat/OpenchatInviteFriends.tsx
  src/components/openchat/OpenchatInviteModal.tsx
  src/components/openchat/OpenchatMessage.tsx
  src/components/openchat/OpenchatMy.tsx
  src/components/openchat/OpenchatMyItem.tsx
  src/components/openchat/OpenchatNav.module.css
  src/components/openchat/OpenchatNav.tsx
  src/components/openchat/OpenchatNavInvite.tsx
  src/components/openchat/OpenchatNavUserItem.tsx
  src/components/openchat/OpenchatNavUsers.tsx
  src/components/openchat/OpenchatSender.tsx
  src/hooks/useDimensions.ts
  src/hooks/useQueryOpenchatById.ts
  src/hooks/useSocket.ts
  src/hooks/useSocketConnect.ts
  src/index.tsx
  src/pages/openchat/Openchat.tsx
  src/pages/openchat/OpenchatRoom.tsx
  src/styles/OpenchatStyle.ts
  src/types/MessageType.ts
  src/types/Openchat.ts
  src/utils/filterOpenChats.ts
  src/utils/formatDate.ts
Labels: enhancement

#36 Feat: 추천친구 메시지 보내기 기능, 유저초대, 채팅방 참여/나가기 기능 추가
  package-lock.json
  package.json
  src/components/auth/SignUpForm4.tsx
  src/components/common/AuthLayout.tsx
  src/components/common/Layout.tsx
  src/components/openchat/OpenchatFriendItem.tsx
  src/components/openchat/OpenchatFriends.tsx
  src/components/openchat/common/OpenchatAvatar.tsx
  src/components/openchat/invite/OpenchatInviteFriendItem.tsx
  src/components/openchat/invite/OpenchatInviteFriends.tsx
  src/components/openchat/invite/OpenchatInviteModal.tsx
  src/components/openchat/invite/OpenchatInviteModalOld.tsx
  src/components/openchat/list/OpenchatCategory.tsx
  src/components/openchat/list/OpenchatFriendItem.tsx
  src/components/openchat/list/OpenchatFriends.tsx
  src/components/openchat/list/OpenchatItem.tsx
  src/components/openchat/list/OpenchatItemSkeleton.tsx
  src/components/openchat/list/OpenchatMy.tsx
  src/components/openchat/list/OpenchatMyItem.tsx
  src/components/openchat/list/OpenchatTopAppbar.tsx
  src/components/openchat/new/OpenchatCreate.tsx
  src/components/openchat/room/MenuToggle.module.css
  src/components/openchat/room/MenuToggle.tsx
  src/components/openchat/room/OpenchatMessage.tsx
  src/components/openchat/room/OpenchatNav.module.css
  src/components/openchat/room/OpenchatNav.tsx
  src/components/openchat/room/OpenchatNavInvite.tsx
  src/components/openchat/room/OpenchatNavUserItem.tsx
  src/components/openchat/room/OpenchatNavUsers.tsx
  src/components/openchat/room/OpenchatSender.tsx
  src/hooks/useMutationCreateChat.ts
  src/hooks/useMutationNewOpenchat.ts
  src/hooks/useMutationOpenchatPatchs.ts
  src/hooks/useMutationSignUp.ts
  src/hooks/useQueryOpenchatById.ts
  src/hooks/useQueryOpenchats.ts
  src/hooks/useSocket.ts
  src/index.tsx
  src/pages/auth/SignIn.tsx
  src/pages/openchat/Openchat.tsx
  src/pages/openchat/OpenchatRoom.tsx
  src/styles/CropperStyles.ts
  src/utils/filterOpenChats.ts
Labels: enhancement

#37 Feat: 오픈채팅기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/auth/SignUpForm4.tsx
  src/components/common/AuthLayout.tsx
  src/components/common/Layout.tsx
  src/components/common/Sidebar.tsx
  src/components/openchat/OpenchatCategory.tsx
  src/components/openchat/OpenchatItem.tsx
  src/components/openchat/OpenchatMy.tsx
  src/components/openchat/OpenchatMyItem.tsx
  src/components/openchat/common/OpenchatAvatar.tsx
  src/components/openchat/invite/OpenchatInviteFriendItem.tsx
  src/components/openchat/invite/OpenchatInviteFriends.tsx
  src/components/openchat/invite/OpenchatInviteModal.tsx
  src/components/openchat/invite/OpenchatInviteModalOld.tsx
  src/components/openchat/list/OpenchatCategory.tsx
  src/components/openchat/list/OpenchatFriendItem.tsx
  src/components/openchat/list/OpenchatFriends.tsx
  src/components/openchat/list/OpenchatItem.tsx
  src/components/openchat/list/OpenchatItemSkeleton.tsx
  src/components/openchat/list/OpenchatMy.tsx
  src/components/openchat/list/OpenchatMyItem.tsx
  src/components/openchat/list/OpenchatTopAppbar.tsx
  src/components/openchat/new/OpenchatCreate.tsx
  src/components/openchat/room/MenuToggle.module.css
  src/components/openchat/room/MenuToggle.tsx
  src/components/openchat/room/OpenchatMessage.tsx
  src/components/openchat/room/OpenchatNav.module.css
  src/components/openchat/room/OpenchatNav.tsx
  src/components/openchat/room/OpenchatNavInvite.tsx
  src/components/openchat/room/OpenchatNavUserItem.tsx
  src/components/openchat/room/OpenchatNavUsers.tsx
  src/components/openchat/room/OpenchatSender.tsx
  src/hooks/useDimensions.ts
  src/hooks/useMutationCreateChat.ts
  src/hooks/useMutationNewOpenchat.ts
  src/hooks/useMutationOpenchatPatchs.ts
  src/hooks/useMutationSignUp.ts
  src/hooks/useQueryOpenchatById.ts
  src/hooks/useQueryOpenchats.ts
  src/index.tsx
  src/libs/firestoreChatConverter.ts
  src/libs/mui.ts
  src/pages/Openchat.tsx
  src/pages/auth/SignIn.tsx
  src/pages/openchat/Openchat.tsx
  src/pages/openchat/OpenchatRoom.tsx
  src/styles/CropperStyles.ts
  src/styles/OpenchatStyle.ts
  src/types/Openchat.ts
  src/types/User.ts
  src/utils/filterOpenChats.ts
  src/utils/formatDate.ts
Labels: enhancement

#42 Fix: 오픈채팅방 참여인원 제대로 안나오는 버그 수정
  .github/workflows/firebase-hosting-pull-request.yml
  src/hooks/useQueryOpenchats.ts
  src/utils/filterOpenChats.ts
Labels: bug

#50 Docs: 오픈채팅, 인증 관련 readme 수정
  README.md
  public/images/login-page.png
  public/images/openchat-chatting.gif
  public/images/openchat-invite.gif
  public/images/openchat-leave.gif
  public/images/openchat-new.gif
  public/images/signup-page.png
Labels: documentation

#69 Feat: 날짜별 채팅 정렬 기능 추가
  src/components/openchat/list/OpenchatMy.tsx
  src/components/openchat/list/OpenchatMyItem.tsx
  src/components/openchat/room/OpenchatDateGroup.tsx
  src/components/openchat/room/OpenchatNav.tsx
  src/hooks/useMutationNewOpenchat.ts
  src/hooks/useQueryOpenchatById.ts
  src/hooks/useQueryOpenchats.ts
  src/pages/openchat/Openchat.tsx
  src/pages/openchat/OpenchatRoom.tsx
  src/styles/OpenchatStyle.ts
  src/types/OpenchatType.ts
  src/utils/filterOpenChats.ts
Labels: enhancement

#72 Feat: 날짜별 채팅 정렬 기능 추가
  .firebase/hosting.YnVpbGQ.cache
  src/components/chat/DatePlaceholder.tsx
  src/components/chat/Message.tsx
  src/styles/chat/DatePlaceholderStyles.ts
  src/styles/chat/MessageStyles.ts
Labels: enhancement
